// Clinical preset data — DarDoc Healthcare's real protocols.
// Sources: "Weight_Management_GLP1_Protocol_UAE Updated.pdf" (Dr. Sami M.
// Yesuf / DarDoc Team, v1.2 June 2026) for GLP-1 data, and
// "Peptide protocol 101.xlsx" (PROTOCOLS MASTER + Benefit Matrix +
// Assesment sheets) for peptide data and the intake question set.

const GLP1_MEDICATIONS = {
  "Wegovy": {
    generic: "semaglutide", route: "injection", frequency: "weekly", halfLifeHours: 168,
    doses: ["0.25mg", "0.5mg", "1mg", "1.7mg", "2.4mg"],
    administration: "Subcutaneous injection once weekly in the abdomen, thigh, or upper arm. Rotate injection sites.",
    titration: [
      { dose: "0.25mg", weeks: 4, note: "Starting dose" },
      { dose: "0.5mg", weeks: 4, note: "First escalation" },
      { dose: "1mg", weeks: 4, note: "Second escalation" },
      { dose: "1.7mg", weeks: 4, note: "Third escalation" },
      { dose: "2.4mg", weeks: null, note: "Maintenance dose — if not tolerated, may remain at 1.7mg" },
    ],
  },
  "Mounjaro": {
    generic: "tirzepatide", route: "injection", frequency: "weekly", halfLifeHours: 120,
    doses: ["2.5mg", "5mg", "7.5mg", "10mg", "12.5mg", "15mg"],
    administration: "Subcutaneous injection once weekly. If a dose is missed, take within 4 days (96 hours); otherwise skip.",
    titration: [
      { dose: "2.5mg", weeks: 4, note: "Starting dose" },
      { dose: "5mg", weeks: 4, note: "First escalation" },
      { dose: "7.5mg", weeks: 4, note: "Second escalation" },
      { dose: "10mg", weeks: 4, note: "Third escalation" },
      { dose: "12.5mg", weeks: 4, note: "Fourth escalation" },
      { dose: "15mg", weeks: null, note: "Maximum dose" },
    ],
  },
  "Wegovy Pill": {
    generic: "oral semaglutide 25mg (SNAC absorption enhancer)", route: "oral", frequency: "daily", halfLifeHours: 168,
    doses: ["1.5mg", "4mg", "9mg", "25mg"],
    administration: "Take 1 tablet on an empty stomach (after ≥8h fasting), swallow with up to 120 mL plain water, then wait 30 minutes before eating or drinking anything else.",
    titration: [
      { dose: "1.5mg", weeks: 4, note: "Days 1–30 — initial tolerability" },
      { dose: "4mg", weeks: 4, note: "Days 31–60 — increase if tolerated" },
      { dose: "9mg", weeks: 4, note: "Days 61–90 — further escalation" },
      { dose: "25mg", weeks: null, note: "Day 91+ — target maintenance dose" },
    ],
  },
  "Foundayo": {
    generic: "orforglipron", route: "oral", frequency: "daily", halfLifeHours: 168,
    doses: ["0.8mg", "2.5mg", "5.5mg", "9mg", "14.5mg", "17.2mg"],
    administration: "Take once daily with or without food, any time of day. No water restrictions or waiting periods. No cold-chain storage required.",
    titration: [
      { dose: "0.8mg", weeks: 4, note: "Starting dose" },
      { dose: "2.5mg", weeks: 4, note: "First escalation" },
      { dose: "5.5mg", weeks: 4, note: "Second escalation" },
      { dose: "9mg", weeks: 4, note: "Third escalation" },
      { dose: "14.5mg", weeks: 4, note: "Fourth escalation" },
      { dose: "17.2mg", weeks: null, note: "Maximum dose" },
    ],
  },
  "Rybelsus": {
    generic: "oral semaglutide (off-label for weight — T2D indication)", route: "oral", frequency: "daily", halfLifeHours: 168,
    doses: ["3mg", "7mg", "14mg"],
    administration: "Take on an empty stomach upon waking with no more than 120 mL plain water. Wait ≥30 minutes before eating, drinking, or taking other medications. Swallow whole.",
    titration: [
      { dose: "3mg", weeks: 4, note: "Starting dose" },
      { dose: "7mg", weeks: 4, note: "First escalation" },
      { dose: "14mg", weeks: null, note: "Maximum approved dose" },
    ],
  },
  "Ozempic": {
    generic: "semaglutide (off-label for weight — T2D indication)", route: "injection", frequency: "weekly", halfLifeHours: 168,
    doses: ["0.25mg", "0.5mg", "1mg", "2mg"],
    administration: "Subcutaneous injection once weekly, abdomen/thigh/upper arm, rotating sites.",
    titration: [
      { dose: "0.25mg", weeks: 4, note: "Starting dose" },
      { dose: "0.5mg", weeks: 4, note: "First escalation" },
      { dose: "1mg", weeks: 4, note: "Second escalation" },
      { dose: "2mg", weeks: null, note: "Maximum approved diabetes dose" },
    ],
  },
};

// Eligibility / safety reference for GLP-1 therapy (UAE protocol §3, §6.8).
const GLP1_ELIGIBILITY = {
  adultBmi: "BMI ≥30 kg/m² (obesity), or ≥27 kg/m² with at least one weight-related comorbidity",
  adolescentCriteria: "Age 12–17: BMI ≥95th percentile for age/sex, or ≥85th percentile with one comorbidity, plus guardian consent and specialist supervision",
  comorbidities: ["Type 2 diabetes or prediabetes (HbA1c 5.7–6.4%)", "Hypertension", "Dyslipidemia requiring pharmacotherapy", "Obstructive sleep apnea", "NAFLD/MASLD", "Cardiovascular disease", "PCOS", "Osteoarthritis related to excess weight"],
  absoluteContraindications: ["Personal or family history of medullary thyroid carcinoma (MTC)", "Multiple endocrine neoplasia type 2 (MEN 2)", "Known hypersensitivity", "Pregnancy or planned pregnancy", "Breastfeeding", "Severe GI disease including gastroparesis", "Active inflammatory bowel disease", "History of pancreatitis"],
  relativeContraindications: ["History of gallbladder disease", "Mild–moderate renal impairment (eGFR 30–89)", "Pre-existing thyroid disease", "Diabetic retinopathy", "History of depression or suicidal ideation", "Concurrent insulin or sulfonylurea use", "Age ≥70 years"],
  redFlags: ["Severe abdominal pain (possible pancreatitis) — stop medication and seek urgent care", "Persistent vomiting with dehydration", "Severe allergic reaction (rash, swelling, difficulty breathing)", "New neck lump or thyroid swelling", "Signs of hypoglycemia (if on diabetes medications)", "Jaundice or severe right-upper-quadrant pain", "Changes in mood, depression, or suicidal thoughts"],
  discontinueIf: ["Confirmed pancreatitis (do not restart GLP-1 therapy)", "Severe allergic reaction", "Pregnancy", "Severe/intolerable GI side effects despite dose reduction", "No weight loss after 6 months at maximum tolerated dose"],
};

// Weekly pharmacokinetic phases shown on the patient dashboard (injectables)
const PK_PHASES_WEEKLY = [
  { name: "Dose Taken",    color: "#1E4C4E", range: [0, 6],     desc: "Medication administered. Absorption is beginning under the skin." },
  { name: "Taking Effect", color: "#B98A1F", range: [6, 24],    desc: "Active absorption phase. You may begin to notice reduced hunger and appetite." },
  { name: "Peak Action",   color: "#C96A2B", range: [24, 48],   desc: "Peak blood concentration. Maximum appetite suppression and best results window." },
  { name: "Cruise",        color: "#2F6FAE", range: [48, 96],   desc: "Steady therapeutic level. Sustained effect — this is your sweet spot." },
  { name: "Winding Down",  color: "#6C4FB0", range: [96, 144],  desc: "Levels gradually declining. Appetite may begin to return slightly." },
  { name: "Pre-Dose",      color: "#54706F", range: [144, 168], desc: "Lowest level of the cycle. Prepare your next dose." },
];

// Daily phases (oral / daily-dosed programs)
const PK_PHASES_DAILY = [
  { name: "Dose Taken",  color: "#1E4C4E", range: [0, 1],   desc: "Dose taken. Absorption begins." },
  { name: "Absorbing",   color: "#B98A1F", range: [1, 4],   desc: "Medication absorbing. Follow your intake instructions." },
  { name: "Active",      color: "#C96A2B", range: [4, 12],  desc: "Active level building through the day." },
  { name: "Maintaining", color: "#2F6FAE", range: [12, 24], desc: "Sustained daily level until your next dose." },
];

// Check-in symptom dimensions (ported from glp1-patient check-in, generalised)
const SYMPTOMS = [
  { key: "hunger",       label: "Hunger / Appetite", options: ["Absent", "Low", "Moderate", "High"], alertOn: [] },
  { key: "nausea",       label: "Nausea",            options: ["None", "Mild", "Moderate", "Severe"], alertOn: ["Severe"] },
  { key: "vomiting",     label: "Vomiting",          options: ["None", "Once", "Few times", "Frequent"], alertOn: ["Few times", "Frequent"] },
  { key: "constipation", label: "Constipation",      options: ["None", "Mild", "Moderate", "Severe"], alertOn: ["Severe"] },
  { key: "diarrhea",     label: "Diarrhea",          options: ["None", "Mild", "Moderate", "Severe"], alertOn: ["Severe"] },
  { key: "fatigue",      label: "Fatigue / Energy",  options: ["Energetic", "Normal", "Tired", "Exhausted"], alertOn: ["Exhausted"] },
  { key: "dizziness",    label: "Dizziness",         options: ["None", "Mild", "Moderate", "Severe"], alertOn: ["Severe"] },
  { key: "injectionSite",label: "Dose-site / Local reaction", options: ["None", "Redness", "Swelling", "Painful"], alertOn: ["Painful"] },
  { key: "mood",         label: "Mood",              options: ["Great", "Good", "Low", "Very low"], alertOn: ["Very low"] },
  { key: "abdominalPain",label: "Abdominal pain",    options: ["None", "Mild", "Moderate", "Severe"], alertOn: ["Severe"] },
];

// ── Peptide protocol library — source of truth: DarDoc "PROTOCOLS MASTER" /
// "Fusion Protocol" sheets in Peptide protocol 101.xlsx.
const PEPTIDE_PROTOCOLS = {
  "BPC-157": [
    { strength: "2000mcg/ml in 5ml Vial", doseAmount: "0.15 ml (15 units)", doseVolume: "0.15 ml (15 units)", time: "Once daily, same time each day, empty stomach (preferably morning)", protocolType: "Standard Protocol", route: "Subcutaneous injection", duration: "33 Days", cycle: "4-12 weeks depending on injury", summary: "BPC-157 2000mcg/ml taken 15 units daily (Vial lasts 33 days)" },
  ],
  "BPC-157 Capsules": [
    { strength: "500 mcg Capsules", doseAmount: "500 mcg", doseVolume: "1 capsule", time: "Once daily", protocolType: "Standard Protocol", route: "Oral capsules", duration: "30 Days", cycle: "3 months+", summary: "BPC-157 Capsules 1 capsule daily (30-count bottle)" },
    { strength: "500 mcg Capsules", doseAmount: "1000 mcg", doseVolume: "2 capsules", time: "Twice daily", protocolType: "Alternative Protocol", route: "Oral capsules", duration: "30 Days", cycle: "3 months+", summary: "BPC-157 Capsules 2 capsules daily (60-count, 2 bottles)" },
  ],
  "Epitalon": [
    { strength: "10 mg/ml in 5 ml vial", doseAmount: "2000 mcg (2mg)", doseVolume: "1 ml full needle", time: "Every 3 days (morning), total dose 50mg over 15 days", protocolType: "Standard Protocol", route: "Subcutaneous injection", duration: "15 Days (5 doses)", cycle: "Repeat every 6 months", summary: "Epitalon 10mg/vial, 1ml every 3 days, repeat every 6 months" },
  ],
  "CJC-1295": [
    { strength: "1000 mcg/ml in 5ml vial", doseAmount: "100 mcg", doseVolume: "0.1 ml (10 units)", time: "5 days on / 2 days off", protocolType: "Standard Protocol", route: "Subcutaneous injection", duration: "10 Weeks", cycle: "8-10 weeks max, repeat after 6 months", summary: "CJC-1295 taken 10 units, 5 days on / 2 off" },
  ],
  "Ipamorelin": [
    { strength: "2000mcg/ml in 5ml Vial", doseAmount: "200 mcg", doseVolume: "0.1 ml (10 units)", time: "5 days on / 2 days off, preferably evening", protocolType: "Standard Protocol", route: "Subcutaneous injection", duration: "10 Weeks", cycle: "At least 3 months break required", summary: "Ipamorelin taken 10 units evening, 5 days on / 2 off" },
  ],
  "Sermorelin": [
    { strength: "10000 mcg/ml in 5 ml vial", doseAmount: "0.2-0.4 ml", doseVolume: "0.2 ml (25 injections) or 0.4 ml (12 injections)", time: "Once daily at bedtime, rotate injection site", protocolType: "Standard Protocol", route: "Subcutaneous injection", duration: "12-25 Days", cycle: "Can alternate with CJC/Ipamorelin", summary: "Sermorelin nightly — alternative to CJC/Ipamorelin" },
  ],
  "CJC/Ipamorelin Blend": [
    { strength: "1000mcg/ml plus 2000mcg/ml in 5ml vial", doseAmount: "100mcg/200mcg", doseVolume: "0.10 ml", time: "5 out of 7 nights before bedtime, empty stomach", protocolType: "Standard Protocol", route: "Subcutaneous injection", duration: "10 Weeks (50 injections)", cycle: "Same as CJC-1295", summary: "CJC/Ipamorelin Blend 0.1ml, 5 nights/week" },
  ],
  "Thymosin Alpha-1": [
    { strength: "3000mcg/ml in 5ml Vial", doseAmount: "0.15 ml (15 units)", doseVolume: "0.15 ml (15 units)", time: "Once daily in belly fat area until vial is empty (Option 1)", protocolType: "Preferred Protocol", route: "Subcutaneous injection", duration: "33 Days", cycle: "Repeat if needed after physician evaluation", summary: "Thymosin Alpha-1 daily, 33-day vial" },
    { strength: "3000mcg/ml in 5ml Vial", doseAmount: "60 units (0.55 ml)", doseVolume: "0.55 ml", time: "2 times per week in belly fat area (Option 2)", protocolType: "Alternative Protocol", route: "Subcutaneous injection", duration: "4-6 Weeks", cycle: "Repeat if needed after physician evaluation", summary: "Thymosin Alpha-1 twice weekly" },
  ],
  "Thymosin Beta-4": [
    { strength: "3000 mcg/ml 5ml Vial", doseAmount: "0.25 ml", doseVolume: "0.25 ml", time: "Daily for 4-6 weeks", protocolType: "Standard Protocol", route: "Subcutaneous injection", duration: "20 Days", cycle: "4-12 weeks per injury needs", summary: "Thymosin Beta-4 daily (20-day vial)" },
  ],
  "PT-141": [
    { strength: "10 mg/ml in 2 ml vial", doseAmount: "0.1-0.2 ml", doseVolume: "0.1-0.2 ml", time: "As needed, 30 min–6h before activity. Men start 0.1ml (max 0.2ml); women 0.2ml. Max twice/week", protocolType: "Standard Protocol", route: "Subcutaneous injection", duration: "10 Doses", cycle: "On demand, max twice a week", summary: "PT-141 injection as needed, max 2x/week" },
  ],
  "PT-141 Nasal": [
    { strength: "10 mg in 15 ml bottle", doseAmount: "", doseVolume: "1-2 pumps each nostril", time: "As needed before sexual activity, up to 2-3x/day. May combine with oxytocin", protocolType: "Alternative Protocol", route: "Intranasal spray", duration: "~30-50 uses", cycle: "On demand", summary: "PT-141 nasal spray, 1-2 pumps as needed" },
  ],
  "GHK-Cu": [
    { strength: "10 mg/ml in 5 ml vial", doseAmount: "1 mg", doseVolume: "0.1 ml (10 units)", time: "Daily for 6 weeks", protocolType: "Initial Protocol", route: "Subcutaneous injection", duration: "50 Days", cycle: "6 weeks on, 4-6 weeks off", summary: "GHK-Cu 0.1 ml (10 units) daily — initial dose, vial lasts 50 days" },
    { strength: "10 mg/ml in 5 ml vial", doseAmount: "1.5 mg", doseVolume: "0.15 ml (15 units)", time: "Daily for 6 weeks", protocolType: "Suggested Protocol", route: "Subcutaneous injection", duration: "33 Days", cycle: "6 weeks on, 4-6 weeks off", summary: "GHK-Cu 0.15 ml (15 units) daily — suggested dose, vial lasts 33 days" },
    { strength: "10 mg/ml in 5 ml vial", doseAmount: "2 mg", doseVolume: "0.2 ml (20 units)", time: "Daily for 6 weeks", protocolType: "Experienced Protocol", route: "Subcutaneous injection", duration: "25 Days", cycle: "6 weeks on, 4-6 weeks off", summary: "GHK-Cu 0.2 ml (20 units) daily — experienced dose, vial lasts 25 days" },
  ],
  "GHK-Cu Facial Serum": [
    { strength: "0.3% serum (HY 2% & Dexpanthenol 0.5%)", doseAmount: "", doseVolume: "Apply thin layer", time: "Daily at night", protocolType: "Skincare Protocol", route: "Topical serum", duration: "Continuous", cycle: "Ongoing", summary: "GHK-Cu facial serum applied nightly" },
  ],
  "GHK-Cu Scalp Foam": [
    { strength: "0.1-0.15% scalp foam", doseAmount: "", doseVolume: "Massage into scalp", time: "Daily at night", protocolType: "Hair Protocol", route: "Topical foam", duration: "Continuous", cycle: "Ongoing", summary: "GHK-Cu scalp foam applied nightly" },
  ],
  "MOTS-C": [
    { strength: "10 mg/ml in 5 ml vial", doseAmount: "10 mg", doseVolume: "1 ml full syringe", time: "Once weekly before exercise (Greenfield's — preferred)", protocolType: "Preferred Protocol", route: "Subcutaneous injection", duration: "Up to 10 weeks/year", cycle: "1-2 cycles/year, 3-6 months between", summary: "MOTS-C 10mg once weekly before exercise" },
    { strength: "10 mg/ml in 5 ml vial", doseAmount: "5 mg", doseVolume: "0.5 ml (50 units)", time: "3x weekly for 4-6 weeks, then weekly for 4 weeks (Seed's protocol)", protocolType: "Alternative Protocol", route: "Subcutaneous injection", duration: "4-6 Weeks", cycle: "For metabolic syndrome / insulin resistance", summary: "MOTS-C 5mg, 3x weekly then weekly" },
  ],
  "AOD-9604": [
    { strength: "1200 mcg/ml - 5ml vial", doseAmount: "300 mcg", doseVolume: "0.25 ml (25 units)", time: "Once daily morning, before food/cardio (Preferred)", protocolType: "Preferred Protocol", route: "Subcutaneous injection", duration: "8-16 Weeks", cycle: "4-8 week break before repeating", summary: "AOD-9604 25 units once daily morning" },
    { strength: "1200 mcg/ml - 5ml vial", doseAmount: "250 mcg", doseVolume: "0.20 ml (20 units) x2", time: "Twice daily — morning empty stomach and bedtime 1-4h after meal", protocolType: "Alternative Protocol", route: "Subcutaneous injection", duration: "8-16 Weeks", cycle: "4-8 week break before repeating", summary: "AOD-9604 20 units twice daily" },
  ],
  "Kisspeptin-10": [
    { strength: "100 mcg/ml in 4ml vial", doseAmount: "10 mcg", doseVolume: "0.1 ml (10 units)", time: "Daily before bed", protocolType: "Standard Protocol", route: "Subcutaneous injection", duration: "40 Days max", cycle: "4-8 week break before repeating", summary: "Kisspeptin-10 daily before bed, max 40 days" },
  ],
  "Dihexa Capsules": [
    { strength: "2.5 mg (30 count)", doseAmount: "2.5 mg", doseVolume: "1 capsule", time: "Once to twice daily", protocolType: "Starting Protocol", route: "Oral capsules (IR)", duration: "30 Days", cycle: "Continue as needed", summary: "Dihexa 2.5mg once-twice daily" },
    { strength: "20 mg (30 count)", doseAmount: "20 mg", doseVolume: "1 capsule", time: "Once daily", protocolType: "Advanced Protocol", route: "Oral capsules (IR)", duration: "30 Days", cycle: "Experienced users only", summary: "Dihexa 20mg once daily (advanced dose)" },
  ],
  "DSIP": [
    { strength: "1000 mcg/ml, 2ml", doseAmount: "100 mcg", doseVolume: "0.1 ml (10 units)", time: "3 hours before bedtime; may reduce to 50mcg once stabilised", protocolType: "Standard Protocol", route: "Subcutaneous injection", duration: "30 Days max", cycle: "2-4 week initial phase, then maintenance every 2-3 days", summary: "DSIP nightly, max 40 days continuous" },
  ],
  "Semax": [
    { strength: "3 mg/ml in 10 ml bottle", doseAmount: "", doseVolume: "1-2 puffs each nostril", time: "Daily at night, max 1 month", protocolType: "Preferred Protocol", route: "Intranasal spray", duration: "~1 month", cycle: "4-6 weeks", summary: "Semax nasal spray nightly" },
    { strength: "1 mg/ml, 5 ml", doseAmount: "30 units", doseVolume: "0.1 ml (30 units)", time: "Twice weekly for 4-6 weeks", protocolType: "Alternative Protocol", route: "Subcutaneous injection", duration: "6 Weeks (16 injections)", cycle: "4-6 weeks", summary: "Semax injection twice weekly" },
  ],
  "Selank": [
    { strength: "3 mg/ml in 10 ml bottle", doseAmount: "", doseVolume: "1-2 puffs each nostril", time: "Daily at night", protocolType: "Preferred Protocol", route: "Intranasal spray", duration: "Ongoing", cycle: "4-6 weeks", summary: "Selank nasal spray nightly" },
    { strength: "1 mg/ml, 5 ml", doseAmount: "30 units", doseVolume: "0.1 ml (30 units)", time: "Twice weekly for 4-6 weeks", protocolType: "Alternative Protocol", route: "Subcutaneous injection", duration: "6 Weeks (16 injections)", cycle: "4-6 weeks", summary: "Selank injection twice weekly" },
  ],
  "KPV": [
    { strength: "500 mcg/Capsule", doseAmount: "500 mcg", doseVolume: "1 capsule", time: "Once to twice daily, up to 8-12 weeks", protocolType: "Standard Protocol", route: "Oral capsules (IR, 30 count)", duration: "8-12 Weeks", cycle: "Continue as needed", summary: "KPV capsules once-twice daily" },
    { strength: "2 mg/ml, 4 ml", doseAmount: "10-25 units", doseVolume: "0.1-0.25 ml", time: "Daily for 4-6 weeks (general inflammation)", protocolType: "Injectable Protocol", route: "Subcutaneous injection", duration: "16-40 Days", cycle: "4-6 week break before repeating", summary: "KPV injection daily for stronger anti-inflammatory support" },
  ],
  "KPV + BPC-157": [
    { strength: "500 mcg/250 mcg Capsule", doseAmount: "750 mcg total", doseVolume: "1 capsule", time: "Once or twice daily for 6-8 weeks", protocolType: "Standard Protocol", route: "Oral capsules (IR, 30 count)", duration: "6-8 Weeks", cycle: "Continue as needed", summary: "KPV+BPC-157 1 capsule once-twice daily" },
  ],
  "Tesamorelin": [
    { strength: "10 mg/ml in 6 ml vial", doseAmount: "5-10 units", doseVolume: "0.05-0.1 ml", time: "Once daily, empty stomach (3h no carbs), preferably evening. Start 5 units for 2 weeks, then up to 10 units max", protocolType: "Standard Protocol", route: "Subcutaneous injection", duration: "8 Weeks (~56-60 injections)", cycle: "8-week protocol, then reassess with breaks", summary: "Tesamorelin daily, max 8-week protocol" },
  ],
  "LR3-IGF1": [
    { strength: "100 mcg/ml in 5 ml vial", doseAmount: "20-40 mcg", doseVolume: "0.2-0.4 ml (20-40 units)", time: "Post-workout, never fasted (hypoglycemia risk). Start 20 units/day for 1 week, increase to 40 units/day for up to 30 days", protocolType: "Standard Protocol", route: "Subcutaneous injection", duration: "4-6 week cycle (~16 injections)", cycle: "Equal off-period between cycles", summary: "LR3-IGF1 post-workout, 4-6 week cycle" },
  ],
  "SS-31": [
    { strength: "80 mg/ml in 3.5 ml vial", doseAmount: "5-10 units", doseVolume: "0.05-0.1 ml", time: "Once daily, preferably evening. Do not stack with MOTS-C", protocolType: "Standard Protocol", route: "Subcutaneous injection", duration: "Up to 12 Weeks (~35 injections)", cycle: "Cycle with breaks", summary: "SS-31 daily, up to 12-week protocol" },
  ],
};

// ── Suggested peptides by primary health goal — source of truth: DarDoc
// "Benefit Matrix" sheet (Longevity & Fitness Peptides Program).
const HEALTH_GOAL_PEPTIDES = {
  // "Weight loss" routes to the GLP-1 program — the suggestions here are the
  // GLP-1 medications to refer, not peptides (rendered with a GLP-1 badge).
  "Weight loss": [
    { name: "Wegovy", priority: "Primary" },
    { name: "Mounjaro", priority: "Primary" },
    { name: "Wegovy Pill", priority: "Primary" },
    { name: "Rybelsus", priority: "Primary" },
    { name: "Foundayo", priority: "Primary" },
  ],
  "Healthy aging & longevity": [
    { name: "Epitalon", priority: "Primary" },
    { name: "BPC-157", priority: "Secondary" },
    { name: "Thymosin Beta-4", priority: "Secondary" },
    { name: "CJC-1295", priority: "Secondary" },
    { name: "Ipamorelin", priority: "Secondary" },
    { name: "Sermorelin", priority: "Secondary" },
    { name: "CJC/Ipamorelin Blend", priority: "Secondary" },
    { name: "MOTS-C", priority: "Secondary" },
    { name: "Thymosin Alpha-1", priority: "Secondary" },
    { name: "GHK-Cu", priority: "Secondary" },
  ],
  "Build muscle & recover better": [
    { name: "CJC-1295", priority: "Primary" },
    { name: "Ipamorelin", priority: "Primary" },
    { name: "Sermorelin", priority: "Primary" },
    { name: "CJC/Ipamorelin Blend", priority: "Primary" },
    { name: "Tesamorelin", priority: "Primary" },
    { name: "LR3-IGF1", priority: "Primary" },
    { name: "BPC-157", priority: "Secondary" },
    { name: "Thymosin Beta-4", priority: "Secondary" },
    { name: "MOTS-C", priority: "Secondary" },
    { name: "GHK-Cu", priority: "Secondary" },
  ],
  "Heal injuries & reduce pain": [
    { name: "BPC-157", priority: "Primary" },
    { name: "Thymosin Beta-4", priority: "Primary" },
    { name: "CJC-1295", priority: "Secondary" },
    { name: "Ipamorelin", priority: "Secondary" },
    { name: "Sermorelin", priority: "Secondary" },
    { name: "CJC/Ipamorelin Blend", priority: "Secondary" },
    { name: "GHK-Cu", priority: "Secondary" },
  ],
  "Improve metabolism & reduce belly fat": [
    { name: "MOTS-C", priority: "Primary" },
    { name: "SS-31", priority: "Primary" },
    { name: "CJC-1295", priority: "Secondary" },
    { name: "Ipamorelin", priority: "Secondary" },
    { name: "CJC/Ipamorelin Blend", priority: "Secondary" },
  ],
  "Improve sleep & reset body clock": [
    { name: "Epitalon", priority: "Primary" },
    { name: "DSIP", priority: "Primary" },
    { name: "Semax", priority: "Secondary" },
    { name: "Selank", priority: "Secondary" },
    { name: "CJC-1295", priority: "Secondary" },
    { name: "Ipamorelin", priority: "Secondary" },
    { name: "Sermorelin", priority: "Secondary" },
    { name: "CJC/Ipamorelin Blend", priority: "Secondary" },
  ],
  "Cognitive function & mood enhancement": [
    { name: "Semax", priority: "Primary" },
    { name: "Dihexa Capsules", priority: "Primary" },
    { name: "PT-141", priority: "Secondary" },
    { name: "Selank", priority: "Secondary" },
  ],
  "Sexual health": [
    { name: "PT-141", priority: "Primary" },
    { name: "Kisspeptin-10", priority: "Secondary" },
  ],
  "Immune function & inflammation": [
    { name: "Thymosin Alpha-1", priority: "Primary" },
    { name: "BPC-157", priority: "Secondary" },
    { name: "Thymosin Beta-4", priority: "Secondary" },
    { name: "KPV", priority: "Secondary" },
    { name: "KPV + BPC-157", priority: "Secondary" },
  ],
  "Gut health": [
    { name: "KPV", priority: "Primary" },
    { name: "KPV + BPC-157", priority: "Primary" },
    { name: "BPC-157", priority: "Secondary" },
  ],
  "Skin & hair": [
    { name: "GHK-Cu", priority: "Primary" },
    { name: "GHK-Cu Facial Serum", priority: "Primary" },
    { name: "GHK-Cu Scalp Foam", priority: "Primary" },
    { name: "BPC-157", priority: "Secondary" },
  ],
};

// Clinical reference for the peptide detail panel — source of truth: DarDoc
// "PROTOCOLS MASTER" sheet columns (Target Benefits / Best Use For / How It
// Works / Possible Combinations / Recommended Supplements / Key Blood Tests /
// Most Common Side Effect). Contraindications are conservative defaults
// (not itemised per-peptide in the source sheet) pending physician review.
const PEPTIDE_INFO = {
  "BPC-157": {
    categories: ["Healing", "Gut Health", "Injury Recovery"],
    howItWorks: "A stable pentadecapeptide derived from a gastric protective protein. Supports local healing and angiogenesis for musculoskeletal recovery.",
    targetBenefits: "Soft-tissue repair, tendon/ligament recovery, gut healing",
    bestUseFor: "Musculoskeletal recovery (tendon, ligament, muscle strains) and post-injury tissue support",
    dosageInstructions: "0.15 ml (15 units) once daily for 4–6 weeks, same time each day, empty stomach (preferably morning)",
    administrationRoute: "Subcutaneous injection",
    strengthVolume: "2000 mcg/ml, 5 ml vial",
    treatmentDuration: "4–12 weeks depending on acute vs chronic injury",
    contraindications: "Pregnancy, active malignancy, known hypersensitivity",
    commonSideEffects: "Nausea, headache, dizziness (rare)",
    keyBloodTests: "None routinely required — no known systemic hormonal or metabolic impact",
    recommendedSupplements: "Collagen peptides (10–20 g/day), Vitamin C (500–1000 mg/day), Zinc (15–30 mg/day), Omega-3",
    possibleCombinations: "Thymosin Beta-4 — synergistic tissue repair (local healing + cell migration); GHK-Cu Injection — enhances collagen synthesis",
    whoItsFor: ["Recovering from a musculoskeletal injury (tendon, ligament, muscle strain)", "Persistent joint or soft-tissue pain not resolving on its own", "Recovering from a procedure and wanting faster, higher-quality tissue repair"],
    dailyRoutine: "Inject 0.15 ml (15 Units) once daily, same time each day, on an empty stomach (morning preferred). Standard SubQ into abdominal fat, rotate injection sites (Square Rotation). 5 ml vial lasts 33 days.",
    storageNotes: "Refrigerate 2–8°C, protect from light, swirl only — never shake. Liquid should be clear.",
    onset: "Reduced pain and improved mobility often noticed within 2–3 weeks; full soft-tissue healing builds over the 4–12 week course.",
    missedDose: "Skip and resume next scheduled dose — do not double up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Injection site increasingly red, warm, painful, or pus", "Severe or worsening pain instead of improvement"],
    lifestyleTips: ["Light, pain-free movement (as cleared by doctor) supports healing", "Adequate protein and Omega-3 intake supports tissue repair", "Pause for 48 hours before/after any planned surgical or dental procedure"],
  },
  "BPC-157 Capsules": {
    categories: ["Gut Health", "Healing"],
    howItWorks: "Oral BPC-157 acts locally on gastric mucosa and intestinal repair signaling.",
    targetBenefits: "Gastrointestinal support, gut lining repair",
    bestUseFor: "Gut lining support (IBS-like symptoms, gastritis adjunct), GI recovery",
    dosageInstructions: "One capsule daily (500 mcg), or two capsules daily for stronger effect",
    administrationRoute: "Oral capsules",
    strengthVolume: "500 mcg capsules, 30 or 60-count",
    treatmentDuration: "3 months or more, repeated as needed",
    contraindications: "Pregnancy, active malignancy",
    commonSideEffects: "GI discomfort, bloating",
    keyBloodTests: "None routinely required — local GI action",
    recommendedSupplements: "L-Glutamine (5–10 g/day), Zinc carnosine, multi-strain probiotics",
    possibleCombinations: "KPV Capsules — combined gut mucosal repair + anti-inflammatory action",
    whoItsFor: ["Gastritis, acid reflux, IBS-like symptoms, or ongoing digestive discomfort", "Recovering from a long antibiotic/anti-inflammatory course affecting gut", "Bloating, cramping, or food sensitivities linked to gut inflammation", "Wants gut-lining repair without starting with an injection"],
    dailyRoutine: "One capsule daily on a completely empty stomach — first thing morning (30 min before breakfast) or right before bed (2+ hours after last meal). Swallow whole with 8oz room-temperature water; avoid hot beverages 15 minutes before/after. 30-capsule bottle lasts 30 days.",
    storageNotes: "Cool, dry place; refrigeration recommended to maintain peak potency over 30 days.",
    onset: "Improved digestion and reduced bloating often within 10 days.",
    missedDose: "Skip and resume next scheduled dose — do not double up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Severe or worsening abdominal pain", "Blood in stool"],
    lifestyleTips: ["Avoid irritants (alcohol, spicy foods, processed sugars) during the 30-day reset", "High-quality fermented foods/probiotics can help repopulate gut flora", "Pause for 48 hours before/after any planned procedure"],
  },
  "Epitalon": {
    categories: ["Longevity", "Sleep"],
    howItWorks: "Influences pineal signaling and circadian gene expression, supporting longevity primarily via improved circadian rhythm; telomere-related anti-aging effects remain experimental.",
    targetBenefits: "Sleep regulation, circadian rhythm, experimental longevity",
    bestUseFor: "Longevity-focused patients — indirectly benefits hormonal balance, immune function, and cellular repair via circadian optimization",
    dosageInstructions: "Inject 1 ml (full needle) every 3 days for 15 days — total dose 50 mg. Repeat every 6 months",
    administrationRoute: "Subcutaneous injection",
    strengthVolume: "10 mg/ml, 5 ml vial",
    treatmentDuration: "15-day course, once every 6 months",
    contraindications: "Pregnancy, active malignancy",
    commonSideEffects: "Headache, flushing",
    keyBloodTests: "Baseline CMP ± fasting glucose — general metabolic safety",
    recommendedSupplements: "Melatonin (low dose, 0.3–1 mg if needed), Magnesium glycinate/threonate, Glycine (3 g at night), Vitamin D",
    possibleCombinations: "DSIP — circadian rhythm + sleep quality support; Sermorelin (low dose, advanced users) — sleep/circadian + physiologic GH pulsatility",
    whoItsFor: ["Poor sleep quality, trouble falling asleep, or waking unrefreshed", "Disrupted sleep patterns from shift work, travel, or chronic stress", "Interested in longevity protocols and cellular-aging support"],
    dailyRoutine: "Option A (Normal Cycle): 1.0 ml (100U) every 3 days, 5-dose/15-day cycle; Option B (Intensive Annual): 1.0 ml daily for 10 days (two vials needed). Evening injection preferred, aligning with melatonin production.",
    storageNotes: "Refrigerate; protect from light; do not shake.",
    onset: "Benefits build gradually; most notice improved sleep and recovery 2–4 weeks into the cycle.",
    missedDose: "3-day cycle: shift next injection to keep ~3-day interval. 10-day intensive: take missed dose ASAP and continue daily.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Injection site increasingly red, warm, painful, or pus"],
  },
  "CJC-1295": {
    categories: ["Growth Hormone", "Muscle & Recovery", "Longevity"],
    howItWorks: "Stimulates pituitary GH release via GHRH receptors.",
    targetBenefits: "Growth hormone stimulation, body composition",
    bestUseFor: "Growth hormone stimulation for body composition and recovery support",
    dosageInstructions: "Inject 10 units, 5 days of the week / 2 days off",
    administrationRoute: "Subcutaneous injection",
    strengthVolume: "1000 mcg/ml, 5 ml vial",
    treatmentDuration: "8–10 weeks max, repeat after 6 months",
    contraindications: "Pregnancy, active malignancy, uncontrolled diabetes",
    commonSideEffects: "Flushing, palpitations",
    keyBloodTests: "IGF-1 (baseline GH-axis status), fasting glucose/HbA1c (GH may affect insulin sensitivity)",
    recommendedSupplements: "L-Arginine or L-Citrulline, Zinc & Magnesium (ZMA), adequate protein (1.6–2.0 g/kg)",
    possibleCombinations: "Ipamorelin — classic synergistic GH stimulation via GHRH + ghrelin pathways",
    whoItsFor: ["Working on body recomposition (fat loss while maintaining/building lean muscle)", "Slower recovery, lower energy, or declining skin quality that may be age-related", "Wants a more youthful GH signaling pattern without direct hormone replacement", "Training consistently but not seeing expected recovery/results"],
    dailyRoutine: "Inject 0.10 ml (10 Units) once daily, same time each day on empty stomach (bedtime often preferred); 5 ml vial provides 50 doses over 10 weeks. CRITICAL fasting rule: 2+ hours since last food, water only.",
    storageNotes: "Refrigerate 2–8°C, swirl only; liquid should be clear — discard if cloudy/particulate.",
    onset: "Energy/recovery shifts within 2–4 weeks; body-composition and skin-quality changes build over following weeks.",
    missedDose: "Skip and resume next scheduled dose — do not double up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Persistent numbness/tingling in hands", "Sustained headache, vision changes, unusual fatigue, or palpitations lasting more than a few minutes"],
    lifestyleTips: ["Prioritize 7–8 hours sleep", "Adequate daily protein supports recovery/body-composition goals"],
  },
  "Ipamorelin": {
    categories: ["Growth Hormone", "Muscle & Recovery"],
    howItWorks: "Ghrelin-mimetic that triggers GH release without a cortisol rise.",
    targetBenefits: "GH stimulation, recovery, sleep quality",
    bestUseFor: "Recovery & sleep support via gentle GH stimulation",
    dosageInstructions: "Inject 10 units, 5 days of the week, preferably in the evening",
    administrationRoute: "Subcutaneous injection",
    strengthVolume: "2000 mcg/ml, 5 ml vial",
    treatmentDuration: "10 weeks, then at least 3 months break (safer than CJC-1295 alone)",
    contraindications: "Pregnancy, active malignancy",
    commonSideEffects: "Headache, fatigue",
    keyBloodTests: "IGF-1 (monitor GH response), fasting glucose (metabolic safety)",
    recommendedSupplements: "L-Arginine or L-Citrulline, Zinc & Magnesium (ZMA), adequate protein (1.6–2.0 g/kg)",
    possibleCombinations: "CJC-1295 — improves GH amplitude without raising cortisol or prolactin",
    whoItsFor: ["Struggling with poor-quality/non-restorative sleep", "Slower recovery from training, injury, or general wear and tear", "Age-related changes in body composition, skin quality, or vitality", "Wants a gentler GH-axis option before direct hormone replacement"],
    dailyRoutine: "Inject 0.1 ml (10 Units), 5 days/week, at bedtime on empty stomach; 5 ml vial provides 50 injections (10 weeks). CRITICAL: no food (incl. fat/protein) 2+ hours before injecting; water only; nothing until morning.",
    storageNotes: "Refrigerate 2–8°C; do not shake, swirl only (fragile molecular bond); liquid should be clear.",
    onset: "Better sleep fairly quickly; body composition and recovery changes build over following weeks.",
    missedDose: "Skip and resume next scheduled evening dose — do not double up or inject during the day to catch up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Persistent numbness/tingling in hands (possible carpal tunnel from fluid retention)", "Sustained headache, vision changes, or unusual fatigue"],
    lifestyleTips: ["Prioritize 7–8 hours sleep", "Avoid high-sugar foods in the evening"],
  },
  "Sermorelin": {
    categories: ["Growth Hormone", "Longevity"],
    howItWorks: "Promotes physiologic GH pulsatility.",
    targetBenefits: "Endogenous GH support, age-related GH decline",
    bestUseFor: "Age-related GH decline support (physiologic GH pulsatility)",
    dosageInstructions: "Inject 0.2–0.4 ml once daily at bedtime, rotate injection site",
    administrationRoute: "Subcutaneous injection",
    strengthVolume: "10000 mcg/ml in 5 ml vial",
    treatmentDuration: "12–25 days per vial; can alternate with CJC/Ipamorelin",
    contraindications: "Pregnancy, active malignancy",
    commonSideEffects: "Injection-site irritation",
    keyBloodTests: "IGF-1 (baseline & monitoring), TSH (GH interacts with thyroid axis)",
    recommendedSupplements: "L-Arginine or L-Citrulline, Zinc & Magnesium (ZMA), adequate protein (1.6–2.0 g/kg)",
    possibleCombinations: "Ipamorelin — more physiologic GH pulsatility than Sermorelin alone",
    whoItsFor: ["Wants a gentler, longer-term GH-axis option vs. more intensive protocols", "Gradual age-related changes in sleep, skin, energy, or recovery", "Prefers a well-established peptide with a long clinical track record"],
    dailyRoutine: "Option A: 0.20 ml (20U)/25-day vial; Option B: 0.40 ml (40U)/12-day vial, both at bedtime. CRITICAL fasting rule: inject on empty stomach, at least 2 hours since last food (no fat/protein snacks), water only. Rotate injection site nightly.",
    storageNotes: "Refrigerate 2–8°C, swirl only never shake; liquid should be clear — discard if cloudy or particulate.",
    onset: "Deeper sleep often within first 2 weeks; skin/energy/body-composition changes build over 3–6 months (benefits accumulate — don't judge by week 2).",
    missedDose: "Skip and resume next scheduled evening dose — do not double up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Persistent numbness or tingling in hands", "Injection site increasingly red, warm, painful, or pus"],
    lifestyleTips: ["Keep a steady sleep schedule — injection and bedtime within the same 30-minute window nightly", "Patience: benefits accumulate over 3–6 months"],
  },
  "CJC/Ipamorelin Blend": {
    categories: ["Growth Hormone", "Muscle & Recovery", "Longevity"],
    howItWorks: "Dual GH stimulation via combined GHRH + ghrelin pathways.",
    targetBenefits: "GH stimulation, body composition",
    bestUseFor: "Enhanced GH stimulation for body composition & recovery",
    dosageInstructions: "Inject 0.10 ml subcutaneously, 5 out of 7 nights before bedtime, empty stomach",
    administrationRoute: "Subcutaneous injection",
    strengthVolume: "1000 mcg/ml plus 2000 mcg/ml in 5 ml vial",
    treatmentDuration: "10 weeks (50 injections), same cycle length as CJC-1295",
    contraindications: "Pregnancy, active malignancy, uncontrolled diabetes",
    commonSideEffects: "Water retention, headache",
    keyBloodTests: "IGF-1 (GH monitoring), fasting glucose/HbA1c (insulin sensitivity)",
    recommendedSupplements: "L-Arginine or L-Citrulline, Zinc & Magnesium (ZMA), adequate protein (1.6–2.0 g/kg)",
    possibleCombinations: "AOD-9604 — GH support + fat-loss signaling (metabolic programs)",
    whoItsFor: ["Pursuing meaningful body recomposition (fat loss + lean muscle preservation)", "Wants stronger recovery and sleep support than either peptide alone", "Focused on longevity/performance, willing to commit to a structured protocol", "Ready for a comprehensive GH-axis approach after single-peptide options"],
    dailyRoutine: "Inject 0.10 ml (10 Units), 5 nights ON / 2 nights OFF (e.g., weekdays on, weekends off) — 5 ml vial covers a 10-week cycle. CRITICAL: fast 2+ hours before bedtime injection; nothing but water after injecting until morning.",
    storageNotes: "Must be refrigerated at all times; do not shake (molecular bond is fragile).",
    onset: "Better sleep within 1 week; improved body composition and recovery by weeks 6–10.",
    missedDose: "Skip and resume next scheduled evening dose — do not double up or inject during the day to catch up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Persistent numbness/tingling in hands (possible carpal tunnel from water retention)", "Sustained headache, vision changes, or unusual fatigue"],
    lifestyleTips: ["Prioritize 7–8 hours of sleep", "Avoid high-sugar foods in the evening (insulin blocks GH release)"],
  },
  "Thymosin Alpha-1": {
    categories: ["Immune Function", "Longevity"],
    howItWorks: "Enhances T-cell function and immune signaling.",
    targetBenefits: "Immune modulation, immune resilience",
    bestUseFor: "Immune modulation & resilience, recurrent infections adjunct",
    dosageInstructions: "0.15 ml (15 units) once daily in belly fat area until vial empty, OR 60 units (0.55 ml) twice weekly",
    administrationRoute: "Subcutaneous injection",
    strengthVolume: "3000 mcg/ml, 5 ml vial",
    treatmentDuration: "33 days (daily option) or 4–6 weeks (twice-weekly option)",
    contraindications: "Organ-transplant recipients on immunosuppressants, active malignancy, pregnancy",
    commonSideEffects: "Injection-site reaction, mild fatigue",
    keyBloodTests: "CBC (baseline immune status), CRP (systemic inflammation marker)",
    recommendedSupplements: "Vitamin D, Zinc, Vitamin C, Selenium",
    possibleCombinations: "Repeat if needed after physician evaluation",
    whoItsFor: ["Catching frequent colds/respiratory infections or slow recovery from viral illness", "Managing a chronic inflammatory condition wanting balanced immune support", "Reduced immune resilience following stress, illness, or age", "Seeking immune modulation rather than simple 'boosting'"],
    dailyRoutine: "Option A (Daily): 15 Units (0.15 ml) once daily, ~33-day vial; Option B (Twice Weekly Pulse): 60 Units (0.5 ml) twice/week, 10-dose (5-week) vial. Consistent timing each morning.",
    storageNotes: "Refrigerate 2–8°C, protect from light, do not shake.",
    onset: "Immune resilience builds gradually; most notice improved recovery from routine infections and general vitality within 4–8 weeks.",
    missedDose: "Skip and resume next scheduled dose — do not double up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Injection site increasingly red, warm, painful, or pus", "Fever or new, unusual symptoms after starting the protocol"],
    lifestyleTips: ["Ensure Vitamin D levels are optimal while on this protocol"],
  },
  "Thymosin Beta-4": {
    categories: ["Healing", "Injury Recovery"],
    howItWorks: "Regulates actin dynamics, cell migration, and angiogenesis.",
    targetBenefits: "Tissue repair, injury recovery (experimental)",
    bestUseFor: "Soft-tissue repair & injury recovery (experimental use)",
    dosageInstructions: "Inject 0.25 ml daily for 4–6 weeks",
    administrationRoute: "Subcutaneous injection",
    strengthVolume: "3000 mcg/ml, 5 ml vial",
    treatmentDuration: "4–12 weeks depending on acute vs chronic injury",
    contraindications: "Pregnancy, active malignancy",
    commonSideEffects: "Fatigue, headache",
    keyBloodTests: "None routinely required — investigational use, no known hormonal effect",
    recommendedSupplements: "Omega-3 fatty acids, Vitamin D, Magnesium",
    possibleCombinations: "BPC-157 — most common injury-recovery stack (migration + local repair)",
    whoItsFor: ["Recovering from chronic or slow-healing soft-tissue injury (tendon/muscle/ligament)", "Old injury never fully resolved and still limiting performance", "Post-surgical wanting higher-quality repair with less scar tissue", "Managing chronic inflammation affecting joints/connective tissue"],
    dailyRoutine: "Inject 0.25 ml (25 Units) via insulin syringe, any time of day (morning preferred for circulation); 5 ml vial lasts exactly 20 days. Standard SubQ into abdominal or outer thigh fat, pinch fat, insert fully at 90°, push slowly.",
    storageNotes: "Strictly refrigerated, protect from direct light (keep in box); swirl only, never shake.",
    onset: "Accelerated healing of acute soft-tissue injuries usually felt within first 2–3 weeks.",
    missedDose: "Skip and resume next scheduled dose — do not double up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Injection site increasingly red, warm, painful, or pus", "Feeling generally unwell after injecting"],
    lifestyleTips: ["Light, pain-free movement (as cleared by doctor) helps circulate repair signals", "High Omega-3 (fish oil) intake supports healing signals", "Pause for 48 hours before/after any planned surgical or dental procedure"],
  },
  "PT-141": {
    categories: ["Sexual Health"],
    howItWorks: "Central melanocortin activation (non-hormonal).",
    targetBenefits: "Sexual desire, erectile response",
    bestUseFor: "Erectile response & libido support (central, non-hormonal)",
    dosageInstructions: "Inject 0.1–0.2 ml as needed, 30 min–6h before sexual activity. Men start at 0.1 ml (do not exceed 0.2 ml); women 0.2 ml. Max twice a week",
    administrationRoute: "Subcutaneous injection",
    strengthVolume: "10 mg/ml, 2 ml vial",
    treatmentDuration: "On demand — max twice weekly",
    contraindications: "Uncontrolled hypertension, cardiovascular disease",
    commonSideEffects: "Nausea, transient increase in blood pressure",
    keyBloodTests: "Blood pressure assessment ± lipid profile — cardiovascular risk screening",
    recommendedSupplements: "L-Citrulline or L-Arginine, Zinc, Ashwagandha (if stress-related libido suppression)",
    possibleCombinations: "None specific — on-demand use",
    whoItsFor: ["Reduced libido/sexual desire in either men or women", "Men for whom PDE5 inhibitors (Viagra/Cialis) were insufficient/unsuitable", "Women looking for a non-hormonal option for low sexual desire", "Wants an on-demand option rather than a daily medication"],
    dailyRoutine: "0.2 ml (20U, standard) or 0.1 ml (10U, starter) as needed, injected 4+ hours before activity. MANDATORY blood pressure check — do not use if systolic >140.",
    storageNotes: "Refrigerate; swirl only, never shake.",
    onset: "Strong signal typically 2–6 hours post-administration.",
    missedDose: "Used as needed; there is no missed dose to make up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Persistent or severe headache, chest pain, or visual changes", "Blood pressure remains elevated more than a few hours after use"],
  },
  "PT-141 Nasal": {
    categories: ["Sexual Health"],
    howItWorks: "Activates CNS melanocortin receptors (non-hormonal), same mechanism as injection.",
    targetBenefits: "Sexual desire and arousal",
    bestUseFor: "Low sexual desire / arousal (men & women), on-demand use",
    dosageInstructions: "1–2 pumps in each nostril as needed before sexual activity, up to 2–3 times per day; can be combined with oxytocin",
    administrationRoute: "Intranasal spray",
    strengthVolume: "10 mg in 15 ml bottle",
    treatmentDuration: "On demand",
    contraindications: "Uncontrolled hypertension, cardiovascular disease",
    commonSideEffects: "Nausea, flushing",
    keyBloodTests: "Blood pressure check (clinical, not lab) — CV safety",
    recommendedSupplements: "L-Citrulline or L-Arginine, Zinc, Ashwagandha (if stress-related)",
    possibleCombinations: "None specific — on-demand use",
    whoItsFor: ["Reduced libido/sexual desire in either men or women", "Prefers a nasal-spray format over injection", "Wants an on-demand option rather than a daily medication"],
    dailyRoutine: "1–2 pumps per nostril, 1–2 hours before activity. MANDATORY blood pressure check — do not use if systolic >140.",
    storageNotes: "Cool, dry place, protect from light.",
    onset: "Effect typically within 1–2 hours of use.",
    missedDose: "Used as needed; there is no missed dose to make up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Persistent or severe headache, chest pain, or visual changes", "Blood pressure remains elevated more than a few hours after use"],
  },
  "GHK-Cu": {
    categories: ["Skin & Hair", "Healing", "Longevity"],
    howItWorks: "Activates collagen and repair gene expression.",
    targetBenefits: "Tissue repair signaling, skin & hair support (advanced protocols)",
    bestUseFor: "Tissue repair signaling, skin & hair support",
    dosageInstructions: "Inject 1–2 mg (10–20 units) daily for 6 weeks",
    administrationRoute: "Subcutaneous injection",
    strengthVolume: "10 mg/ml, 5 ml vial",
    treatmentDuration: "6 weeks on, 4–6 weeks off before repeating",
    contraindications: "Known copper sensitivity, pregnancy",
    commonSideEffects: "Injection-site irritation",
    keyBloodTests: "None routinely required — minimal systemic exposure",
    recommendedSupplements: "Collagen peptides, Vitamin C, Biotin (if deficient), Silica",
    possibleCombinations: "BPC-157 — repair + collagen/skin signaling (post-procedure recovery); Tesamorelin",
    whoItsFor: ["Wants whole-body skin and connective-tissue support, not one area", "Age-related loss of skin firmness/elasticity or overall vitality", "Interested in longevity protocols for tissue repair/cellular defense", "Wants a systemic effect complementing topical skin/hair treatments"],
    dailyRoutine: "Once daily injection into abdominal fat: Option A 0.1 ml (10U)/50-day vial, B 0.15 ml (15U)/33-day vial, or C 0.2 ml (20U)/25-day vial. Known for a brief 'sting' (normal, fades ~60 sec). Rotate injection sites daily.",
    storageNotes: "Refrigeration mandatory (keeps copper-peptide bond stable); liquid is a natural deep blue; swirl gently, never shake.",
    onset: "Skin clarity/energy often improve within 3 weeks; joint and deeper structural benefits after ~6 weeks.",
    missedDose: "Skip and resume next scheduled dose — do not double up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Injection site increasingly red, warm, painful, or pus", "Unusual fatigue, metallic taste, or unresolving nausea (possible copper-zinc imbalance)"],
    lifestyleTips: ["MANDATORY: take an oral zinc supplement (15–30mg) while on protocol to keep minerals balanced", "Support with Vitamin C and Biotin", "Pause for 48 hours before/after any planned surgical or dental procedure"],
  },
  "GHK-Cu Facial Serum": {
    categories: ["Skin & Hair"],
    howItWorks: "Enhances fibroblast activity locally.",
    targetBenefits: "Skin regeneration, collagen stimulation",
    bestUseFor: "Skin rejuvenation, collagen support, post-procedure care",
    dosageInstructions: "Apply daily at night",
    administrationRoute: "Facial serum (topical)",
    strengthVolume: "0.3% serum with HY 2% & Dexpanthenol 0.5%",
    treatmentDuration: "Continuous use",
    contraindications: "Known copper sensitivity",
    commonSideEffects: "Local skin irritation",
    keyBloodTests: "None required",
    recommendedSupplements: "Collagen peptides, Vitamin C, Biotin (if deficient), Silica",
    possibleCombinations: "SS-31 (systemic longevity support)",
    whoItsFor: ["Focused on face/skin quality — fine lines, firmness, texture", "Recovering from an aesthetic procedure (laser, microneedling, peels)"],
    dailyRoutine: "Apply 3–5 drops to clean, dry skin once or twice daily, massage in, follow with moisturizer. Avoid combining with strong retinoids, high-concentration Vitamin C, or chemical exfoliants — space by hours. Post-procedure: start only after skin barrier closes (24–48 hrs).",
    storageNotes: "Cool, dark place; refrigeration extends shelf life and preserves the copper-peptide bond, do not freeze. Natural pale blue tint is normal — brown/green discoloration means oxidized, stop use and request replacement. Use within 90 days of opening.",
    onset: "Smoother texture/subtle glow in 3–4 weeks, visible firming/line-softening over 8–12 weeks.",
    missedDose: "Resume the next day — topical peptides tolerate short interruptions without losing progress.",
    redFlags: ["Spreading redness, rash, hives, or swelling beyond application area", "Skin increasingly irritated after the first week (may signal pH/combination issue)"],
    lifestyleTips: ["Daily SPF 30+ on the face is non-negotiable — unprotected UV undoes gains", "Adequate protein, Vitamin C, and zinc support collagen synthesis"],
  },
  "GHK-Cu Scalp Foam": {
    categories: ["Skin & Hair"],
    howItWorks: "Supports follicle signaling and scalp repair.",
    targetBenefits: "Hair follicle support, scalp health",
    bestUseFor: "Hair thinning support, scalp health",
    dosageInstructions: "Apply on the scalp with gentle massage at night",
    administrationRoute: "Scalp foam (topical)",
    strengthVolume: "0.1–0.15% scalp foam",
    treatmentDuration: "Continuous use",
    contraindications: "Known copper sensitivity",
    commonSideEffects: "Scalp irritation",
    keyBloodTests: "None required",
    recommendedSupplements: "Collagen peptides, Vitamin C, Biotin (if deficient), Silica",
    possibleCombinations: "IGF-1 (advanced protocols)",
    whoItsFor: ["Experiencing hair thinning, wants scalp/follicle health support"],
    dailyRoutine: "One pump massaged into scalp daily, leave on 6+ hours (overnight ideal), don't wash out immediately.",
    storageNotes: "Cool, dark place; refrigeration extends shelf life, do not freeze. Use within 90 days of opening.",
    onset: "Less shedding in 6–8 weeks, density improvements build over 4–6 months with continued use.",
    missedDose: "Resume the next day — topical peptides tolerate short interruptions without losing progress.",
    redFlags: ["Scalp irritation persisting despite reduced frequency", "Spreading redness, rash, hives, or swelling beyond application area"],
    lifestyleTips: ["Adequate protein, Vitamin C, and zinc support collagen synthesis"],
  },
  "MOTS-C": {
    categories: ["Metabolism", "Longevity", "Weight Loss"],
    howItWorks: "Mitochondrial-derived peptide improving cellular energy use.",
    targetBenefits: "Metabolic flexibility, insulin sensitivity",
    bestUseFor: "Metabolic flexibility & insulin sensitivity support",
    dosageInstructions: "10 mg (1 ml) once weekly before exercise (preferred), OR 5 mg 3x weekly for 4–6 weeks then weekly for 4 weeks",
    administrationRoute: "Subcutaneous injection",
    strengthVolume: "10 mg/ml, 5 ml vial",
    treatmentDuration: "4–6 week cycle, max ~10 weeks/year, 1–2 cycles/year with 3–6 months between",
    contraindications: "Pregnancy, active malignancy",
    commonSideEffects: "Injection-site pain",
    keyBloodTests: "Fasting glucose/HbA1c (metabolic baseline), lipid profile (cardiometabolic risk)",
    recommendedSupplements: "Alpha-lipoic acid, Berberine (if insulin resistance present), Magnesium, Omega-3",
    possibleCombinations: "AOD-9604 — metabolic flexibility + fat metabolism; CJC/Ipamorelin (advanced) — cellular energy + GH-mediated body composition. Do NOT stack with SS-31",
    whoItsFor: ["Managing insulin resistance, pre-diabetes, or improving metabolic health", "Athlete or active adult wanting improved endurance and reduced exercise fatigue", "Noticing age-related metabolic slowdown despite diet and exercise", "Looking to support fat-and-sugar fuel flexibility at the cellular level"],
    dailyRoutine: "Three options: (A) Athletic/Performance — 1.0 ml (100 Units) once weekly; (B) Metabolic Reset — 0.5 ml (50 Units) three times/week; (C) Starter Phase — 1.0 ml weekly for 4 weeks. Best taken 30–60 minutes before the most intense exercise session — inject slowly to minimize pressure (larger-volume injection).",
    storageNotes: "Highly sensitive — keep in the back of the fridge, never shake, only swirl. Liquid should be clear.",
    onset: "Boost in workout endurance and recovery within 2–3 weeks.",
    missedDose: "Take same day if remembered; otherwise skip and resume next scheduled dose.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Injection site increasingly red, warm, painful, or pus", "Unusual fatigue or muscle weakness that doesn't improve with rest"],
  },
  "AOD-9604": {
    categories: ["Weight Loss", "Metabolism"],
    howItWorks: "Fragment of human growth hormone designed to stimulate fat breakdown (lipolysis) and reduce fat storage (lipogenesis) with minimal GH/IGF-1 activity.",
    targetBenefits: "Fat-loss support (adjunct), metabolic support (experimental)",
    bestUseFor: "Fat-loss support adjunct to lifestyle/medical weight programs — athletes and active individuals aiming to reduce visceral or stubborn fat",
    dosageInstructions: "300 mcg (25 units) once daily morning before food/cardio (preferred), OR 250 mcg (20 units) twice daily",
    administrationRoute: "Subcutaneous injection",
    strengthVolume: "1200 mcg/ml, 5 ml vial",
    treatmentDuration: "Standard 8–12 weeks, maximum 16 weeks, then 4–8 week break",
    contraindications: "Pregnancy, breastfeeding, active malignancy",
    commonSideEffects: "Headache, nausea; injection-site irritation",
    keyBloodTests: "Fasting glucose ± HbA1c (baseline metabolic status), lipid profile (optional but useful in weight-loss programs)",
    recommendedSupplements: "High-quality protein, Omega-3, Green tea extract (EGCG), L-Carnitine",
    possibleCombinations: "CJC/Ipamorelin — fat metabolism + GH-mediated recovery; MOTS-C — metabolic flexibility. Avoid combining with GLP-1 purely for fat loss unless clearly justified",
    whoItsFor: ["Focused on fat loss, particularly stubborn abdominal/visceral fat", "Working on body recomposition alongside diet and training", "Prefers a targeted fat-metabolism option over a full GH-axis peptide"],
    dailyRoutine: "Option A (Standard): 0.15 ml (15U) once daily, 33-day vial; Option B (High Frequency): 0.20 ml (20U) twice daily (morning & bedtime), 12.5-day vial. Best first thing in the morning, fasted, wait 30 min before eating. For maximum effect, do 20–30 min light cardio 30 min after injecting.",
    storageNotes: "Keep refrigerated; swirl only; ensure liquid is clear before use.",
    onset: "Visible fat loss in stubborn areas usually begins after 6–8 weeks of consistent use.",
    missedDose: "Skip and resume next scheduled dose — do not double up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Injection site increasingly red, warm, painful, or pus", "Persistent palpitations or chest discomfort"],
    lifestyleTips: ["20–30 min light cardio (walking/cycling) 30 minutes after injection for maximum effect"],
  },
  "Kisspeptin-10": {
    categories: ["Sexual Health", "Hormonal Health"],
    howItWorks: "Stimulates GnRH, increasing LH/FSH to support ovulatory and sex-hormone signaling.",
    targetBenefits: "Fertility support (ovulation induction), libido/sexual function via HPG-axis signaling",
    bestUseFor: "Fertility & reproductive hormone signaling support (selected cases)",
    dosageInstructions: "0.1 ml (10 units) daily before bed, max 40 days (full vial)",
    administrationRoute: "Subcutaneous injection",
    strengthVolume: "100 mcg/ml, 4 ml vial",
    treatmentDuration: "Maximum 40 days continuous, 4–8 week break before repeat",
    contraindications: "Hormone-sensitive cancers, pregnancy",
    commonSideEffects: "Headache, flushing; possible transient hormone fluctuations",
    keyBloodTests: "LH, FSH, Estradiol, Progesterone (cycle/ovulation status); Total testosterone, Prolactin (men — endocrine screen)",
    recommendedSupplements: "Vitamin D, Zinc, Folate (women), Omega-3",
    possibleCombinations: "KPV",
    whoItsFor: ["Low libido, low energy, or declining natural hormone symptoms", "Younger patients wanting hormone-axis support without suppressing own production", "Planning for fertility, needs an option preserving reproductive function", "Looking for an alternative to hormone replacement therapy"],
    dailyRoutine: "Inject 10 Units (0.1 ml) once daily at bedtime, standard SubQ into abdomen; 4 ml vial lasts 40 days.",
    storageNotes: "Refrigerate and protect from light; swirl gently.",
    onset: "Improved libido/hormonal vitality usually noted by end of the 40-day cycle.",
    missedDose: "Skip and resume next scheduled dose — do not double up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Persistent headache, vision changes, or unusual mood shifts", "Injection site increasingly red, warm, painful, or pus"],
  },
  "Dihexa Capsules": {
    categories: ["Cognitive & Mood"],
    howItWorks: "HGF/c-Met pathway-linked synaptogenesis signaling (investigational).",
    targetBenefits: "Cognitive support / memory (experimental)",
    bestUseFor: "Cognitive support & memory, low starting dose (2.5mg) for new users, 20mg for experienced users",
    dosageInstructions: "2.5mg once-to-twice daily, or 20mg once daily (advanced/experienced users only)",
    administrationRoute: "Oral capsules (immediate release)",
    strengthVolume: "2.5mg or 20mg, 30-count",
    treatmentDuration: "Continue as needed",
    contraindications: "Pregnancy, active malignancy (theoretical growth-factor concern)",
    commonSideEffects: "Headache, nausea; jitteriness/insomnia sometimes",
    keyBloodTests: "None routinely required — baseline CMP reasonable for general safety with new neuroactive agents",
    recommendedSupplements: "Omega-3 (DHA), Choline (citicoline or alpha-GPC), B-complex vitamins",
    possibleCombinations: "Semax, Selank",
    whoItsFor: ["Memory lapses, word-finding difficulty, or age-related cognitive slowdown", "Mentally demanding role wanting focus/learning support", "Persistent brain fog unresolved by lifestyle changes", "Prefers an oral capsule over an injectable cognitive peptide"],
    dailyRoutine: "One capsule daily, morning with a full glass of water — 2.5 mg (conservative) or 20 mg (intensive) depending on prescription.",
    storageNotes: "Cool, dry place; refrigeration is a safe optional extra step.",
    onset: "Sharper focus within 2 weeks; memory improvement over 1–3 months.",
    missedDose: "Skip and resume next scheduled morning dose — do not double up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Sustained insomnia, racing thoughts, or unusual anxiety", "Concerning mood changes"],
    lifestyleTips: ["Pair with a high-DHA Omega-3 (fish oil) supplement to provide building blocks for new synapses"],
  },
  "DSIP": {
    categories: ["Sleep", "Longevity"],
    howItWorks: "Modulates sleep-related neuropeptide signaling (mechanism in humans not fully established).",
    targetBenefits: "Sleep initiation/quality support (experimental)",
    bestUseFor: "Sleep initiation & sleep quality support",
    dosageInstructions: "100 mcg (10 units) subcutaneously 3 hours before bedtime; may reduce to 50mcg once stabilised",
    administrationRoute: "Subcutaneous injection",
    strengthVolume: "1000 mcg/ml, 2 ml vial",
    treatmentDuration: "Initial 2–4 weeks; maximum 30–40 days continuous, then maintenance every 2–3 days",
    contraindications: "Pregnancy",
    commonSideEffects: "Drowsiness, vivid dreams, headache",
    keyBloodTests: "None routinely required — consider TSH if sleep issues suggest thyroid disturbance",
    recommendedSupplements: "Magnesium glycinate, L-theanine, Glycine",
    possibleCombinations: "Epitalon — sleep initiation + circadian rhythm alignment",
    whoItsFor: ["Struggling to fall asleep, particularly with racing mind or stress", "Waking unrefreshed despite adequate time in bed", "Wants a non-sedating alternative to traditional sleep medications", "Wants to avoid morning grogginess from benzodiazepines/sleep aids"],
    dailyRoutine: "Option A (Standard): 100 mcg (0.1 ml) as needed or daily, 20 doses/2ml vial; Option B (Maintenance): 50 mcg (0.05 ml) daily, 40 doses/2ml vial. Administer exactly 3 hours before intended bedtime, at night only.",
    storageNotes: "Refrigerate; do not shake.",
    onset: "Most patients notice deeper, more restorative sleep within 5–10 nights of consistent use.",
    missedDose: "Skip; used as-needed for sleep support, so a missed night is not a concern.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Persistent daytime grogginess affecting driving or work", "Sleep does not improve after 3–4 weeks of consistent use"],
  },
  "Semax": {
    categories: ["Cognitive & Mood"],
    howItWorks: "Nootropic peptide influencing neurotrophic and neurotransmitter pathways (investigational).",
    targetBenefits: "Cognitive performance, focus, stress resilience (experimental)",
    bestUseFor: "Focus, cognitive performance & stress resilience",
    dosageInstructions: "1–2 puffs each nostril daily at night, max one month (nasal); OR 30 units twice weekly for 4–6 weeks (injection)",
    administrationRoute: "Intranasal spray or subcutaneous injection",
    strengthVolume: "3 mg/ml in 10 ml bottle (nasal); 1 mg/ml in 5 ml (injection)",
    treatmentDuration: "1 month (nasal) or 6 weeks (injection)",
    contraindications: "Pregnancy, seizure disorder (caution)",
    commonSideEffects: "Nasal irritation, headache; agitation in sensitive users",
    keyBloodTests: "None routinely required",
    recommendedSupplements: "Omega-3 (DHA-rich), B-complex vitamins, Rhodiola (low dose)",
    possibleCombinations: "Selank — focus + anxiety modulation (neurocognitive balance)",
    whoItsFor: ["High-demand professional/student needing sustained focus under cognitive load", "Struggling with brain fog, mental fatigue, or attention difficulties", "Wants cognitive support through stress or sleep deprivation", "Wants a fast-onset nootropic in a convenient nasal-spray format"],
    dailyRoutine: "Nasal: 1–2 puffs each nostril, daily at night, max one month. Injection: 0.30 ml (30 Units) twice weekly (every 3 days). Morning use preferred (activating, avoid after 3pm).",
    storageNotes: "Refrigerate 2–8°C, do not freeze. Nasal spray: use within 30 days of first use, discard if cloudy/odd smell. Injection: swirl only, never shake.",
    onset: "Nasal effect within 15–30 minutes; injection reaches steady levels over the first few days; cognitive benefits consolidate over 2–4 weeks.",
    missedDose: "Skip — do not double up, and do not dose late in the day to catch up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Persistent agitation, insomnia, or mood changes", "Sustained headache or elevated blood pressure"],
    lifestyleTips: ["Complements good sleep, not a substitute for it", "Can feel more intense on empty stomach — a light breakfast smooths onset"],
  },
  "Selank": {
    categories: ["Cognitive & Mood", "Sleep"],
    howItWorks: "Modulates GABAergic/anxiolytic signaling (investigational).",
    targetBenefits: "Anxiety/stress modulation, calm focus (experimental)",
    bestUseFor: "Anxiety & stress modulation, calm focus",
    dosageInstructions: "1–2 puffs each nostril daily at night (nasal); OR 30 units twice weekly for 4–6 weeks (injection)",
    administrationRoute: "Intranasal spray or subcutaneous injection",
    strengthVolume: "3 mg/ml in 10 ml bottle (nasal); 1 mg/ml in 5 ml (injection)",
    treatmentDuration: "Ongoing (nasal) or 6 weeks (injection)",
    contraindications: "Pregnancy",
    commonSideEffects: "Drowsiness, nasal irritation",
    keyBloodTests: "None routinely required",
    recommendedSupplements: "Magnesium threonate or glycinate, L-theanine, Ashwagandha",
    possibleCombinations: "Semax — calm focus + cognitive performance",
    whoItsFor: ["Anxiety, stress, or racing thoughts affecting daily focus", "Wants calm, clear-headed focus without sedation"],
    dailyRoutine: "1–2 puffs each nostril daily at night (nasal); OR 30 units twice weekly for 4–6 weeks (injection).",
    storageNotes: "Refrigerate 2–8°C, do not freeze; swirl only, never shake (injection).",
    onset: "Calming effect often within days; anxiety/stress modulation builds over 2–4 weeks.",
    missedDose: "Skip — do not double up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Drowsiness, nasal irritation"],
  },
  "KPV": {
    categories: ["Gut Health", "Immune Function", "Healing"],
    howItWorks: "Tripeptide derived from alpha-MSH; anti-inflammatory signaling in gut/immune pathways.",
    targetBenefits: "Gut inflammation support (IBS-like symptoms adjunct), skin inflammation support (experimental)",
    bestUseFor: "Gut inflammation support (IBS-like symptoms adjunct)",
    dosageInstructions: "One capsule (500 mcg) once-twice daily up to 8–12 weeks; OR 10–25 units injected daily for 4–6 weeks (stronger anti-inflammatory support)",
    administrationRoute: "Oral capsules or subcutaneous injection",
    strengthVolume: "500 mcg/capsule; 2 mg/ml in 4 ml vial (injection)",
    treatmentDuration: "8–12 weeks (oral) or 4–6 weeks with 4–6 week break (injection)",
    contraindications: "Pregnancy, active malignancy",
    commonSideEffects: "GI discomfort (rare), headache; injection-site irritation and occasional fatigue (injectable)",
    keyBloodTests: "CRP (optional baseline inflammation marker); CBC + CRP if used for inflammatory complaints (injection)",
    recommendedSupplements: "Curcumin (bioavailable), Omega-3 fatty acids, Glutamine, Probiotics",
    possibleCombinations: "BPC-157 Capsules — gut inflammation control + mucosal repair",
    whoItsFor: ["Ongoing gut inflammation, recurring digestive flare-ups, chronic bowel conditions", "Managing inflammatory skin conditions", "Joint pain/swelling tied to autoimmune or inflammatory drivers", "Wants targeted anti-inflammatory support without broad immune suppression"],
    dailyRoutine: "Injection: 15 Units (0.15 ml) once daily, ~33-day vial. Capsule: one capsule daily on empty stomach, 30-day bottle. Injection best for systemic inflammation (joints, psoriasis, eczema); capsule best for localized gut conditions.",
    storageNotes: "Injection form: refrigerate 2–8°C, swirl, do not shake. Capsule form: cool, dry place, refrigeration optional.",
    onset: "Cooling of inflammation (skin/gut/joints) within 7–10 days.",
    missedDose: "Skip and resume next scheduled dose — do not double up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Injection site increasingly red, warm, painful, or pus"],
  },
  "KPV + BPC-157": {
    categories: ["Gut Health", "Healing"],
    howItWorks: "KPV reduces inflammatory signaling; BPC-157 supports mucosal repair pathways.",
    targetBenefits: "Combined gut lining + anti-inflammatory support",
    bestUseFor: "Combined gut repair + anti-inflammatory support",
    dosageInstructions: "One or two capsules daily for 6–8 weeks",
    administrationRoute: "Oral capsules (immediate release, 30-count)",
    strengthVolume: "500 mcg/250 mcg per capsule",
    treatmentDuration: "6–8 weeks",
    contraindications: "Pregnancy, active malignancy",
    commonSideEffects: "GI upset/bloating",
    keyBloodTests: "None routinely required",
    recommendedSupplements: "L-Glutamine, Zinc Carnosine, Omega-3",
    possibleCombinations: "Standalone — already a combination protocol",
    whoItsFor: ["'Leaky gut', chronic bowel inflammation, or gut issues with both inflammation and lining damage", "Recovering from persistent soft-tissue injury where inflammation has slowed healing", "Complex inflammatory skin/joint condition unresolved by a single approach", "Ready for a comprehensive two-phase protocol after single-peptide options"],
    dailyRoutine: "One capsule daily on a completely empty stomach (first thing morning or last thing at night) with 8oz water; avoid eating for 30 minutes. 60-capsule bottle provides a complete 60-day course.",
    storageNotes: "Cool, dry place; refrigeration recommended to maintain potency over the 60-day course.",
    onset: "Reduced inflammation/digestive discomfort typically within 7–10 days; more substantive gut-lining repair builds over the full 60-day course.",
    missedDose: "Skip and resume the next day — do not double up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Severe or worsening abdominal pain", "Blood in stool"],
    lifestyleTips: ["Pause for 48 hours before/after any planned procedure"],
  },
  "Tesamorelin": {
    categories: ["Growth Hormone", "Metabolism", "Longevity"],
    howItWorks: "GHRH analog — binds pituitary GHRH receptors to stimulate natural, pulsatile growth-hormone release, raising IGF-1 within the physiologic range while preserving somatostatin feedback.",
    targetBenefits: "Visceral (belly) fat reduction, improved body composition and lipid profile, lean-mass preservation, tissue repair, potential cognitive support",
    bestUseFor: "Reducing visceral adipose tissue and abdominal/metabolic fat; body recomposition in adults with GH-axis decline",
    dosageInstructions: "Max 10 units (0.1 ml) once daily; start as low as 5 units for the first 2 weeks. Empty stomach (3h no carbs), preferably evening. Max 8-week protocol",
    administrationRoute: "Subcutaneous injection",
    strengthVolume: "10 mg/ml in 6 ml vial",
    treatmentDuration: "8 weeks per protocol, then reassess and cycle with breaks — fat/IGF-1 effects reverse after discontinuation",
    contraindications: "Pregnancy, active malignancy",
    commonSideEffects: "Injection-site redness, arthralgia (joint aches), mild fluid retention/edema, transient rise in blood glucose",
    keyBloodTests: "IGF-1 (confirm response, avoid supraphysiologic levels), fasting glucose/HbA1c (may reduce insulin sensitivity)",
    recommendedSupplements: "Controlled-carb diet, Vitamin D, Omega-3, adequate protein to support lean mass",
    possibleCombinations: "Ipamorelin / CJC-1295 — GH-secretagogue synergy, commonly paired in body-composition protocols",
    whoItsFor: ["Excess visceral/abdominal fat resistant to diet and exercise", "Wants body recomposition alongside GH-axis support", "Under physician supervision for an 8-week structured protocol"],
    dailyRoutine: "Max 10 units (0.1 ml) once daily; start as low as 5 units for the first 2 weeks. Empty stomach (3h no carbs), preferably evening.",
    storageNotes: "Refrigerate 2–8°C, swirl only, never shake.",
    onset: "Body-composition changes typically build over the full 8-week protocol; reassess with doctor at completion.",
    missedDose: "Skip and resume next scheduled dose — do not double up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Injection site increasingly red, warm, painful, or pus", "New joint pain or unusual fluid retention"],
  },
  "LR3-IGF1": {
    categories: ["Muscle & Recovery", "Performance"],
    howItWorks: "Long-R3 analog of IGF-1 (83 aa) with reduced IGFBP binding and a 20–30h half-life; activates the IGF-1 receptor → PI3K/Akt (protein synthesis) and MAPK/ERK (cell proliferation), stimulating muscle satellite cells.",
    targetBenefits: "Muscle hypertrophy and hyperplasia, accelerated recovery, nutrient partitioning, skin and connective-tissue regeneration",
    bestUseFor: "Muscle growth and recovery / body recomposition — experimental, performance context (banned in competitive sport)",
    dosageInstructions: "Start 20 units daily for 1 week, increase to 40 units daily for up to 30 days. Ideally post-workout; never fasted (hypoglycemia risk)",
    administrationRoute: "Subcutaneous injection",
    strengthVolume: "100 mcg/ml in 5 ml vial",
    treatmentDuration: "4–6 week cycle followed by an equal off-period — continuous use desensitizes IGF-1 receptors",
    contraindications: "Pregnancy, active malignancy, history of cancer, diabetes",
    commonSideEffects: "Hypoglycemia (most important), water retention/edema, joint pain, injection-site reaction, fatigue; mitogenic/organ-growth risk with chronic high doses",
    keyBloodTests: "Fasting glucose/HbA1c (hypoglycemia & insulin resistance), IGF-1; screen for cancer/diabetes history (contraindicated)",
    recommendedSupplements: "Post-injection carbohydrates and protein to prevent hypoglycemia; avoid fasted use",
    possibleCombinations: "GH secretagogues (CJC-1295/Ipamorelin) used in some protocols — caution: amplifies total IGF-1 exposure",
    whoItsFor: ["Performance/muscle-growth focused, training consistently with a structured recovery plan", "Wants a short, defined cycle rather than continuous use"],
    dailyRoutine: "Start 20 units daily for 1 week, increase to 40 units daily for up to 30 days. Take post-workout; never fasted (hypoglycemia risk) — always with a carb/protein snack immediately after.",
    storageNotes: "Refrigerate 2–8°C, swirl only, never shake.",
    onset: "Recovery and muscle-growth effects build over the 4–6 week cycle.",
    missedDose: "Skip and resume next scheduled dose — do not double up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Symptoms of low blood sugar (shakiness, sweating, confusion)", "Injection site increasingly red, warm, painful, or pus"],
    lifestyleTips: ["Never inject fasted — always pair with food to prevent hypoglycemia"],
  },
  "SS-31": {
    categories: ["Longevity", "Metabolism", "Cardiovascular"],
    howItWorks: "Mitochondria-targeted tetrapeptide (Szeto–Schiller); selectively binds cardiolipin on the inner mitochondrial membrane, stabilizing cristae, improving electron transport and ATP production while lowering reactive oxygen species.",
    targetBenefits: "Improved mitochondrial energy (ATP) output, reduced oxidative stress, better stamina and recovery, cellular and cardiovascular support",
    bestUseFor: "Mitochondrial support and cellular energy — fatigue, recovery, longevity and age-related bioenergetic decline (investigational)",
    dosageInstructions: "Min 5 to max 10 units (0.1 ml) once daily, preferably evening. Barth-syndrome 40mg doses do NOT apply to longevity protocols",
    administrationRoute: "Subcutaneous injection",
    strengthVolume: "80 mg/ml in 3.5 ml vial",
    treatmentDuration: "Up to 12 weeks per protocol, cycle with breaks",
    contraindications: "Pregnancy, active malignancy",
    commonSideEffects: "Injection-site reactions (redness, irritation) — generally well tolerated",
    keyBloodTests: "None routinely required",
    recommendedSupplements: "CoQ10/ubiquinol, NAD+ precursors (NMN/NR), Magnesium, B-vitamins, Alpha-lipoic acid",
    possibleCombinations: "NAD+ and CoQ10 support. Do NOT stack with MOTS-C",
    whoItsFor: ["Persistent fatigue or reduced stamina despite adequate rest", "Interested in longevity/cellular-energy protocols", "Wants mitochondrial support as part of a broader recovery plan"],
    dailyRoutine: "5–10 units (0.05–0.1 ml) once daily, preferably evening.",
    storageNotes: "Refrigerate 2–8°C, swirl only, never shake.",
    onset: "Improved energy and stamina typically build over several weeks of the 12-week protocol.",
    missedDose: "Skip and resume next scheduled dose — do not double up.",
    redFlags: ["Rash, hives, swelling, or difficulty breathing", "Injection site increasingly red, warm, painful, or pus"],
  },
};

const ACTIVITY_LEVELS = {
  "Sedentary":         { multiplier: 1.2,   desc: "Little or no exercise, desk job" },
  "Lightly Active":    { multiplier: 1.375, desc: "Light exercise or sports 1-3 days/week" },
  "Moderately Active": { multiplier: 1.55,  desc: "Moderate exercise or sports 3-5 days/week" },
  "Very Active":       { multiplier: 1.725, desc: "Hard exercise or sports 6-7 days/week" },
};

const BODY_SHAPES = ["Lean", "Athletic", "Average", "Overweight", "Central/Abdominal fat dominant"];

function calcBMI(heightCm, weightKg) {
  if (!heightCm || !weightKg) return null;
  const m = heightCm / 100;
  return Math.round((weightKg / (m * m)) * 10) / 10;
}

function bmiCategory(bmi) {
  if (bmi == null) return "";
  if (bmi < 18.5) return "Underweight";
  if (bmi < 25) return "Normal weight";
  if (bmi < 30) return "Overweight";
  if (bmi < 35) return "Obesity Class I";
  if (bmi < 40) return "Obesity Class II";
  return "Obesity Class III";
}

// Mifflin-St Jeor
function calcBMR(weightKg, heightCm, age, gender) {
  if (!weightKg || !heightCm || !age) return null;
  const base = 10 * weightKg + 6.25 * heightCm - 5 * age;
  return Math.round(gender === "Female" ? base - 161 : base + 5);
}

// ── Structured intake — source of truth: DarDoc "Assesment" sheet
// (Longevity & Fitness Peptides Program intake spec). Demographics
// (gender/age/height/weight/body-shape/activity-level) are hardcoded fields
// in the wizard's Identity & Demographics step, asked unconditionally to
// every patient per the source spec. `required: true` marks a question the
// doctor must answer before continuing. `conditionalOn.value` may be a
// string or an array of strings (OR match).
const INTAKE_SECTIONS = [
  "Clinical",
  "Primary Health Objectives",
  "Objective-Specific Questions",
];

// Descriptive subtext shown under each health-goal chip (source: Assesment
// sheet Q9 options) — only the 5 goals with an official spec have copy here.
const GOAL_DESCRIPTIONS = {
  "Healthy aging & longevity": "Improve energy, resilience, and long-term health as you age",
  "Build muscle & recover better": "Support muscle growth, strength, and faster recovery from workouts",
  "Heal injuries & reduce pain": "Support healing of muscles, joints, tendons, and ongoing injuries",
  "Improve metabolism & reduce belly fat": "Improve metabolic health, boost energy, and reduce stubborn or visceral belly fat",
  "Improve sleep & reset body clock": "Sleep deeper, fall asleep faster, and restore healthy sleep rhythms",
};

// Goals that route the consultation to the weight-loss / GLP-1 workflow.
const WEIGHT_LOSS_GOALS = ["Weight loss", "Improve metabolism & reduce belly fat"];

const INTAKE_QUESTIONS = [
  // Clinical
  { id: "health_conditions", section: "Clinical", question: "Chronic illnesses history", type: "multiselect", hasGate: true, gateLabel: "Any chronic illnesses?", hasOther: true, hasNotes: true, required: true, options: ["High blood pressure", "High cholesterol", "Prediabetes or diabetes", "Thyroid disorder", "Hormonal imbalance (e.g., low testosterone, PCOS)", "Autoimmune or inflammatory condition", "Chronic joint, muscle, or back pain", "Sleep disorder (insomnia, sleep apnea, etc.)", "Mental health condition (stress, anxiety, depression)"] },
  { id: "allergies", section: "Clinical", question: "Allergy history", type: "multiselect", hasGate: true, gateLabel: "Any known allergies or sensitivities to medications or supplements?", hasOther: true, hasNotes: true, required: true, options: ["Medications", "Vitamins or supplements", "Food allergies", "Environmental allergies"] },
  { id: "is_pregnant", section: "Clinical", question: "Currently pregnant?", type: "select", options: ["No", "Yes"], conditionalOn: { questionId: "gender", value: "Female" }, required: true },
  { id: "is_breastfeeding", section: "Clinical", question: "Currently breastfeeding?", type: "select", options: ["No", "Yes"], conditionalOn: { questionId: "gender", value: "Female" }, required: true },
  { id: "cancer_history", section: "Clinical", question: "Have you or a close family member ever been diagnosed with cancer or any tumor/growth?", type: "select", options: ["No", "Yes - myself", "Yes - a family member", "Yes - both myself and a family member"], hasNotes: true },
  { id: "previous_glp1", section: "Clinical", question: "Previous history of GLP-1/peptide medication use?", type: "select", options: ["No", "Yes"], hasNotes: true },

  // Primary Health Objectives — "Weight loss" is added ahead of the 5
  // officially-documented goals to route into the GLP-1 workflow; the last
  // 5 (Cognitive/Sexual/Immune/Gut/Skin) extend coverage to match the
  // Benefit Matrix's full peptide range (no official assessment copy yet).
  { id: "health_goals", section: "Primary Health Objectives", question: "What are your main health goals? (Select all that apply)", type: "multiselect", hasOther: true, hasNotes: true, options: ["Weight loss", "Healthy aging & longevity", "Build muscle & recover better", "Heal injuries & reduce pain", "Improve metabolism & reduce belly fat", "Improve sleep & reset body clock", "Cognitive function & mood enhancement", "Sexual health", "Immune function & inflammation", "Gut health", "Skin & hair"] },

  // A. Healthy aging & longevity (L1-L5)
  { id: "energy_levels", section: "Objective-Specific Questions", question: "How would you rate your overall energy levels?", type: "select", options: ["Very good", "Good", "Moderate", "Low"], conditionalOn: { questionId: "health_goals", value: "Healthy aging & longevity" } },
  { id: "recovery_decline", section: "Objective-Specific Questions", question: "Do you feel your recovery, resilience, or stamina has declined?", type: "select", options: ["No", "Slightly", "Moderately", "Significantly"], conditionalOn: { questionId: "health_goals", value: "Healthy aging & longevity" } },
  { id: "sick_frequency", section: "Objective-Specific Questions", question: "How often do you get sick (colds, flu, infections)?", type: "select", options: ["Rarely", "1-2 times/year", "3-4 times/year", "Frequently"], conditionalOn: { questionId: "health_goals", value: "Healthy aging & longevity" } },
  { id: "inflammation", section: "Objective-Specific Questions", question: "Do you experience persistent inflammation, aches, or stiffness?", type: "select", options: ["No", "Occasionally", "Often", "Constantly"], conditionalOn: { questionId: "health_goals", value: "Healthy aging & longevity" } },
  { id: "longevity_focus", section: "Objective-Specific Questions", question: "Are you currently focused on long-term health optimization rather than treating a disease?", type: "select", options: ["Yes", "Somewhat", "No"], conditionalOn: { questionId: "health_goals", value: "Healthy aging & longevity" } },

  // B. Build muscle & recover better (B1-B5)
  { id: "training_frequency", section: "Objective-Specific Questions", question: "How often do you train or exercise?", type: "select", options: ["0-1x/week", "2-3x/week", "4-5x/week", "6+ times/week"], conditionalOn: { questionId: "health_goals", value: "Build muscle & recover better" } },
  { id: "muscle_plateau", section: "Objective-Specific Questions", question: "Do you feel your muscle gains or strength have plateaued?", type: "select", options: ["No", "Slightly", "Yes", "Declining"], conditionalOn: { questionId: "health_goals", value: "Build muscle & recover better" } },
  { id: "workout_recovery", section: "Objective-Specific Questions", question: "How well do you recover after workouts?", type: "select", options: ["Very well", "Acceptable", "Poorly", "Need several days"], conditionalOn: { questionId: "health_goals", value: "Build muscle & recover better" } },
  { id: "soreness", section: "Objective-Specific Questions", question: "Do you experience excessive soreness or fatigue after training?", type: "select", options: ["Rarely", "Sometimes", "Often", "Almost always"], conditionalOn: { questionId: "health_goals", value: "Build muscle & recover better" } },
  { id: "lean_muscle_priority", section: "Objective-Specific Questions", question: "Is maintaining lean muscle a priority for you?", type: "select", options: ["Yes", "Somewhat", "Not a priority"], conditionalOn: { questionId: "health_goals", value: "Build muscle & recover better" } },

  // C. Heal Injuries & Reduce Pain (I1-I5)
  { id: "current_injury", section: "Objective-Specific Questions", question: "Do you currently have an injury or chronic pain?", type: "select", options: ["No", "Mild", "Moderate", "Severe"], conditionalOn: { questionId: "health_goals", value: "Heal injuries & reduce pain" } },
  { id: "injury_type", section: "Objective-Specific Questions", question: "What best describes the issue?", type: "select", options: ["Muscle strain", "Tendon/ligament", "Joint pain", "Post-surgery", "Multiple areas"], conditionalOn: { questionId: "health_goals", value: "Heal injuries & reduce pain" } },
  { id: "injury_duration", section: "Objective-Specific Questions", question: "How long has the issue been present?", type: "select", options: ["<1 month", "1-3 months", "3-6 months", ">6 months"], conditionalOn: { questionId: "health_goals", value: "Heal injuries & reduce pain" } },
  { id: "injury_impact", section: "Objective-Specific Questions", question: "Has the injury limited your training or daily activity?", type: "select", options: ["No", "Slightly", "Moderately", "Completely"], conditionalOn: { questionId: "health_goals", value: "Heal injuries & reduce pain" } },
  { id: "conventional_treatments", section: "Objective-Specific Questions", question: "Have conventional treatments helped?", type: "select", options: ["Yes", "Partially", "No"], conditionalOn: { questionId: "health_goals", value: "Heal injuries & reduce pain" } },

  // D. Improve Metabolism & Reduce Belly Fat (M1-M5)
  { id: "fat_storage", section: "Objective-Specific Questions", question: "Where do you tend to store fat the most?", type: "select", options: ["Evenly", "Hips/thighs", "Abdomen/belly", "Mostly visceral/belly"], conditionalOn: { questionId: "health_goals", value: "Improve metabolism & reduce belly fat" } },
  { id: "fat_loss_struggle", section: "Objective-Specific Questions", question: "Have you struggled to lose fat despite diet or exercise?", type: "select", options: ["No", "Occasionally", "Yes", "Long-term struggle"], conditionalOn: { questionId: "health_goals", value: "Improve metabolism & reduce belly fat" } },
  { id: "energy_crashes", section: "Objective-Specific Questions", question: "Do you experience energy crashes or sugar cravings?", type: "select", options: ["Rarely", "Sometimes", "Often", "Daily"], conditionalOn: { questionId: "health_goals", value: "Improve metabolism & reduce belly fat" } },
  { id: "insulin_resistance", section: "Objective-Specific Questions", question: "Have you ever been told you have insulin resistance, prediabetes, or metabolic syndrome?", type: "select", options: ["No", "Borderline", "Yes"], conditionalOn: { questionId: "health_goals", value: "Improve metabolism & reduce belly fat" } },
  { id: "appetite_control", section: "Objective-Specific Questions", question: "Is appetite control a major challenge for you?", type: "select", options: ["No", "Mild", "Moderate", "Severe"], conditionalOn: { questionId: "health_goals", value: "Improve metabolism & reduce belly fat" } },

  // E. Improve Sleep & Reset Your Body Clock (S1-S5)
  { id: "sleep_quality", section: "Objective-Specific Questions", question: "How would you rate your sleep quality?", type: "select", options: ["Very good", "Good", "Poor", "Very poor"], conditionalOn: { questionId: "health_goals", value: "Improve sleep & reset body clock" } },
  { id: "sleep_issue", section: "Objective-Specific Questions", question: "Do you struggle more with falling asleep or staying asleep?", type: "select", options: ["Falling asleep", "Staying asleep", "Both", "Neither"], conditionalOn: { questionId: "health_goals", value: "Improve sleep & reset body clock" } },
  { id: "sleep_hours", section: "Objective-Specific Questions", question: "How many hours of sleep do you get on average?", type: "select", options: ["<5", "5-6", "6-7", "7-8", ">8"], conditionalOn: { questionId: "health_goals", value: "Improve sleep & reset body clock" } },
  { id: "sleep_refreshed", section: "Objective-Specific Questions", question: "Do you wake up feeling refreshed?", type: "select", options: ["Always", "Sometimes", "Rarely", "Never"], conditionalOn: { questionId: "health_goals", value: "Improve sleep & reset body clock" } },
  { id: "sleep_impact", section: "Objective-Specific Questions", question: "Does poor sleep affect your energy, mood, or recovery?", type: "select", options: ["No", "Slightly", "Moderately", "Severely"], conditionalOn: { questionId: "health_goals", value: "Improve sleep & reset body clock" } },

  // Additional goal categories (no official assessment copy — extends the
  // intake to match the Benefit Matrix's full peptide coverage)
  { id: "cognitive_concern", section: "Objective-Specific Questions", question: "What best describes your main concern?", type: "select", options: ["Focus/concentration", "Memory", "Mood", "Mental fatigue"], conditionalOn: { questionId: "health_goals", value: "Cognitive function & mood enhancement" } },
  { id: "sexual_concern", section: "Objective-Specific Questions", question: "What best describes your main concern?", type: "select", options: ["Low libido", "Erectile/arousal response", "Both"], conditionalOn: { questionId: "health_goals", value: "Sexual health" } },
  { id: "immune_frequency", section: "Objective-Specific Questions", question: "How often do you get sick or notice inflammation flare-ups?", type: "select", options: ["Rarely", "1-2 times/year", "3-4 times/year", "Frequently"], conditionalOn: { questionId: "health_goals", value: "Immune function & inflammation" } },
  { id: "gut_symptoms", section: "Objective-Specific Questions", question: "Do you experience ongoing gut symptoms (bloating, IBS-like symptoms, discomfort)?", type: "select", options: ["No", "Occasionally", "Often", "Daily"], conditionalOn: { questionId: "health_goals", value: "Gut health" } },
  { id: "skin_hair_concern", section: "Objective-Specific Questions", question: "What best describes your main concern?", type: "select", options: ["Skin aging/texture", "Hair thinning", "Both"], conditionalOn: { questionId: "health_goals", value: "Skin & hair" } },

  { id: "additional_notes", section: "Objective-Specific Questions", question: "Any additional notes or concerns for the doctor?", type: "text" },
];

// Weight-loss daily calorie target: TDEE minus a 500 kcal deficit, floored at 1200.
function weightLossCalories(tdee) {
  if (!tdee) return null;
  return Math.max(1200, Math.round(tdee) - 500);
}

module.exports = {
  GLP1_MEDICATIONS,
  GLP1_ELIGIBILITY,
  PK_PHASES_WEEKLY,
  PK_PHASES_DAILY,
  SYMPTOMS,
  PEPTIDE_PROTOCOLS,
  HEALTH_GOAL_PEPTIDES,
  PEPTIDE_INFO,
  ACTIVITY_LEVELS,
  BODY_SHAPES,
  INTAKE_SECTIONS,
  INTAKE_QUESTIONS,
  GOAL_DESCRIPTIONS,
  WEIGHT_LOSS_GOALS,
  calcBMI,
  bmiCategory,
  calcBMR,
  weightLossCalories,
};
